### ISSUE TITLE
Include font-weight in fonts option

### ISSUE THREAD

**Issue by jednano** [m18ru/postcss-text-remove-gap#3]
The CSS that defines our fonts does it in such a way that we don't actually specify the entire font name like in the examples in the readme. Instead, we define `font-weight` variations like so:
```css
.regular {
    font: 14px/calc(20/14) source-sans-pro;
    text-remove-gap: both;
}
.light {
    font: light 14px/calc(20/14) source-sans-pro;
    text-remove-gap: both;
}
.semibold {
    font: semibold 14px/calc(20/14) source-sans-pro;
    text-remove-gap: both;
}
```
Notice, the font-weight can sometimes be `light` or `semibold` for this font, in which case, there are different calculations we need to use for the cap and baseline locations.

**Suggestion**

I suggest you allow a configuration like so:

```json
{
  "fonts": [
    {
      "family": "Source Sans Pro",
      "weight": "light",
      "cap": 0.194,
      "baseline": 0.146
    }
  ]
}
```
The `weight` being optional.

What do you think?

**Comment by jednano** [comment]
I built a Sass mixin a while back that did the same thing, but the configuration looked like this:
```scss
    source-sans-light: (
         ascender: -0.038,
              cap: -0.194,
         baseline: -0.146,
        descender:  0.082
    ),
    source-sans-regular: (
         ascender: -0.036,
              cap: -0.198,
         baseline: -0.146,
        descender:  0.070
    ),
    source-sans-semibold: (
         ascender: -0.034,
              cap: -0.200,
         baseline: -0.146,
        descender:  0.060
    )
```
The negatives were for trimming and the positives were for adding more space.

Point is, people might want to trim the font to the ascenders and descenders too, not just the cap and baseline. As such, I think a declaration named `adjust-font-bounds` would be more appropriate than `text-remove-gap`. For example:

```css
.foo {
    font: light 14px/calc(20/14) source-sans-pro;
    adjust-font-bounds: cap baseline;
}
````
